import { CalendarIntegration, CalendarEvent, CalendarConflict, StudySession, Module } from './types';

export class CalendarSyncManager {
  private static readonly GOOGLE_CLIENT_ID = 'your-google-client-id';
  private static readonly MICROSOFT_CLIENT_ID = 'your-microsoft-client-id';

  // Initialize calendar providers
  static async initializeProviders(): Promise<void> {
    // Load Google Calendar API
    if (typeof window !== 'undefined' && !window.gapi) {
      await this.loadScript('https://apis.google.com/js/api.js');
      await new Promise((resolve) => {
        window.gapi.load('auth2:client', resolve);
      });
    }

    // Load Microsoft Graph API
    if (typeof window !== 'undefined' && !window.Msal) {
      await this.loadScript('https://alcdn.msauth.net/browser/2.14.2/js/msal-browser.min.js');
    }
  }

  private static loadScript(src: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = src;
      script.onload = () => resolve();
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  // Google Calendar Integration
  static async connectGoogleCalendar(): Promise<CalendarIntegration | null> {
    try {
      await this.initializeProviders();
      
      await window.gapi.client.init({
        clientId: this.GOOGLE_CLIENT_ID,
        discoveryDocs: ['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'],
        scope: 'https://www.googleapis.com/auth/calendar'
      });

      const authInstance = window.gapi.auth2.getAuthInstance();
      const user = await authInstance.signIn();
      const profile = user.getBasicProfile();
      const authResponse = user.getAuthResponse();

      const integration: CalendarIntegration = {
        id: `google_${Date.now()}`,
        provider: 'google',
        name: 'Google Calendar',
        email: profile.getEmail(),
        isConnected: true,
        accessToken: authResponse.access_token,
        syncEnabled: true,
        lastSync: new Date().toISOString(),
        syncSettings: {
          autoCreateEvents: true,
          syncCompletedSessions: false,
          includeBreaks: false,
          eventPrefix: '[Study]',
          reminderMinutes: 10,
          colorCoding: true,
          conflictResolution: 'notify'
        }
      };

      return integration;
    } catch (error) {
      console.error('Google Calendar connection failed:', error);
      return null;
    }
  }

  // Microsoft Outlook Integration
  static async connectOutlookCalendar(): Promise<CalendarIntegration | null> {
    try {
      await this.initializeProviders();

      const msalConfig = {
        auth: {
          clientId: this.MICROSOFT_CLIENT_ID,
          authority: 'https://login.microsoftonline.com/common',
          redirectUri: window.location.origin
        }
      };

      const msalInstance = new window.Msal.PublicClientApplication(msalConfig);
      
      const loginRequest = {
        scopes: ['https://graph.microsoft.com/calendars.readwrite']
      };

      const response = await msalInstance.loginPopup(loginRequest);
      
      const integration: CalendarIntegration = {
        id: `outlook_${Date.now()}`,
        provider: 'outlook',
        name: 'Outlook Calendar',
        email: response.account.username,
        isConnected: true,
        accessToken: response.accessToken,
        syncEnabled: true,
        lastSync: new Date().toISOString(),
        syncSettings: {
          autoCreateEvents: true,
          syncCompletedSessions: false,
          includeBreaks: false,
          eventPrefix: '[Study]',
          reminderMinutes: 10,
          colorCoding: true,
          conflictResolution: 'notify'
        }
      };

      return integration;
    } catch (error) {
      console.error('Outlook Calendar connection failed:', error);
      return null;
    }
  }

  // Create calendar event from study session
  static async createCalendarEvent(
    integration: CalendarIntegration,
    session: StudySession,
    module: Module
  ): Promise<boolean> {
    const event: CalendarEvent = {
      id: `study_${session.id}`,
      title: `${integration.syncSettings.eventPrefix} ${module.code} - ${module.name}`,
      description: `Study session for ${module.name}\nDuration: ${session.duration} minutes\nGenerated by RandStudy`,
      startTime: this.convertToCalendarTime(session.date, session.startTime),
      endTime: this.convertToCalendarTime(session.date, session.endTime),
      color: module.color,
      source: 'randstudy',
      studySessionId: session.id,
      reminders: [integration.syncSettings.reminderMinutes]
    };

    try {
      if (integration.provider === 'google') {
        return await this.createGoogleEvent(integration, event);
      } else if (integration.provider === 'outlook') {
        return await this.createOutlookEvent(integration, event);
      }
      return false;
    } catch (error) {
      console.error('Failed to create calendar event:', error);
      return false;
    }
  }

  private static async createGoogleEvent(
    integration: CalendarIntegration,
    event: CalendarEvent
  ): Promise<boolean> {
    try {
      const response = await window.gapi.client.calendar.events.insert({
        calendarId: 'primary',
        resource: {
          summary: event.title,
          description: event.description,
          start: {
            dateTime: event.startTime,
            timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
          },
          end: {
            dateTime: event.endTime,
            timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
          },
          reminders: {
            useDefault: false,
            overrides: event.reminders?.map(minutes => ({
              method: 'popup',
              minutes
            }))
          },
          colorId: this.getGoogleColorId(event.color)
        }
      });

      return response.status === 200;
    } catch (error) {
      console.error('Google Calendar event creation failed:', error);
      return false;
    }
  }

  private static async createOutlookEvent(
    integration: CalendarIntegration,
    event: CalendarEvent
  ): Promise<boolean> {
    try {
      const response = await fetch('https://graph.microsoft.com/v1.0/me/events', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${integration.accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          subject: event.title,
          body: {
            contentType: 'text',
            content: event.description
          },
          start: {
            dateTime: event.startTime,
            timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
          },
          end: {
            dateTime: event.endTime,
            timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
          },
          reminderMinutesBeforeStart: event.reminders?.[0] || 10
        })
      });

      return response.ok;
    } catch (error) {
      console.error('Outlook Calendar event creation failed:', error);
      return false;
    }
  }

  // Sync study sessions to calendar
  static async syncStudySessions(
    integration: CalendarIntegration,
    sessions: StudySession[],
    modules: Module[]
  ): Promise<{ success: number; failed: number }> {
    let success = 0;
    let failed = 0;

    for (const session of sessions) {
      if (!session.completed || integration.syncSettings.syncCompletedSessions) {
        const module = modules.find(m => m.id === session.moduleId);
        if (module) {
          const created = await this.createCalendarEvent(integration, session, module);
          if (created) {
            success++;
          } else {
            failed++;
          }
        }
      }
    }

    // Update last sync time
    integration.lastSync = new Date().toISOString();

    return { success, failed };
  }

  // Check for calendar conflicts
  static async checkConflicts(
    integration: CalendarIntegration,
    sessions: StudySession[]
  ): Promise<CalendarConflict[]> {
    const conflicts: CalendarConflict[] = [];

    try {
      const events = await this.getCalendarEvents(integration, sessions[0]?.date, sessions[sessions.length - 1]?.date);
      
      for (const session of sessions) {
        const sessionStart = new Date(this.convertToCalendarTime(session.date, session.startTime));
        const sessionEnd = new Date(this.convertToCalendarTime(session.date, session.endTime));

        const conflictingEvent = events.find(event => {
          const eventStart = new Date(event.startTime);
          const eventEnd = new Date(event.endTime);
          
          return (sessionStart < eventEnd && sessionEnd > eventStart) && event.source !== 'randstudy';
        });

        if (conflictingEvent) {
          conflicts.push({
            id: `conflict_${session.id}`,
            studySessionId: session.id,
            conflictingEvent,
            suggestedResolution: 'reschedule',
            alternativeSlots: this.findAlternativeSlots(sessionStart, sessionEnd, events)
          });
        }
      }
    } catch (error) {
      console.error('Failed to check conflicts:', error);
    }

    return conflicts;
  }

  private static async getCalendarEvents(
    integration: CalendarIntegration,
    startDate: string,
    endDate: string
  ): Promise<CalendarEvent[]> {
    try {
      if (integration.provider === 'google') {
        return await this.getGoogleEvents(integration, startDate, endDate);
      } else if (integration.provider === 'outlook') {
        return await this.getOutlookEvents(integration, startDate, endDate);
      }
      return [];
    } catch (error) {
      console.error('Failed to get calendar events:', error);
      return [];
    }
  }

  private static async getGoogleEvents(
    integration: CalendarIntegration,
    startDate: string,
    endDate: string
  ): Promise<CalendarEvent[]> {
    const response = await window.gapi.client.calendar.events.list({
      calendarId: 'primary',
      timeMin: new Date(startDate).toISOString(),
      timeMax: new Date(endDate).toISOString(),
      singleEvents: true,
      orderBy: 'startTime'
    });

    return response.result.items.map((item: any) => ({
      id: item.id,
      title: item.summary,
      description: item.description || '',
      startTime: item.start.dateTime || item.start.date,
      endTime: item.end.dateTime || item.end.date,
      source: item.description?.includes('RandStudy') ? 'randstudy' : 'external'
    }));
  }

  private static async getOutlookEvents(
    integration: CalendarIntegration,
    startDate: string,
    endDate: string
  ): Promise<CalendarEvent[]> {
    const response = await fetch(
      `https://graph.microsoft.com/v1.0/me/calendarview?startDateTime=${startDate}&endDateTime=${endDate}`,
      {
        headers: {
          'Authorization': `Bearer ${integration.accessToken}`
        }
      }
    );

    const data = await response.json();
    return data.value.map((item: any) => ({
      id: item.id,
      title: item.subject,
      description: item.body.content || '',
      startTime: item.start.dateTime,
      endTime: item.end.dateTime,
      source: item.body.content?.includes('RandStudy') ? 'randstudy' : 'external'
    }));
  }

  private static findAlternativeSlots(
    originalStart: Date,
    originalEnd: Date,
    existingEvents: CalendarEvent[]
  ): string[] {
    const alternatives: string[] = [];
    const duration = originalEnd.getTime() - originalStart.getTime();
    
    // Try slots before and after the original time
    for (let offset of [-60, -30, 30, 60, 120]) { // minutes
      const newStart = new Date(originalStart.getTime() + offset * 60000);
      const newEnd = new Date(newStart.getTime() + duration);
      
      const hasConflict = existingEvents.some(event => {
        const eventStart = new Date(event.startTime);
        const eventEnd = new Date(event.endTime);
        return newStart < eventEnd && newEnd > eventStart;
      });

      if (!hasConflict) {
        alternatives.push(newStart.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
      }
    }

    return alternatives.slice(0, 3); // Return top 3 alternatives
  }

  private static convertToCalendarTime(date: string, time: string): string {
    const [timePart, period] = time.split(' ');
    const [hours, minutes] = timePart.split(':').map(Number);
    
    let hour24 = hours;
    if (period === 'PM' && hours !== 12) hour24 += 12;
    if (period === 'AM' && hours === 12) hour24 = 0;

    const dateTime = new Date(date);
    dateTime.setHours(hour24, minutes, 0, 0);
    
    return dateTime.toISOString();
  }

  private static getGoogleColorId(hexColor?: string): string {
    // Map hex colors to Google Calendar color IDs
    const colorMap: { [key: string]: string } = {
      '#3B82F6': '1', // Blue
      '#EF4444': '11', // Red
      '#10B981': '10', // Green
      '#F59E0B': '5', // Yellow
      '#8B5CF6': '3', // Purple
      '#EC4899': '4', // Pink
      '#06B6D4': '6', // Cyan
      '#84CC16': '2'  // Lime
    };
    
    return colorMap[hexColor || '#3B82F6'] || '1';
  }

  // Disconnect calendar integration
  static async disconnectCalendar(integration: CalendarIntegration): Promise<boolean> {
    try {
      if (integration.provider === 'google') {
        const authInstance = window.gapi.auth2.getAuthInstance();
        await authInstance.signOut();
      } else if (integration.provider === 'outlook') {
        // Microsoft logout would be handled by the MSAL instance
      }
      
      integration.isConnected = false;
      integration.accessToken = undefined;
      integration.refreshToken = undefined;
      
      return true;
    } catch (error) {
      console.error('Failed to disconnect calendar:', error);
      return false;
    }
  }
}